name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        if: false
        uses: actions/checkout@v4

      - name: test
        run: |
          echo "$ANDROID_HOME"

          ls "$ANDROID_HOME/emulator"
          "$ANDROID_HOME/emulator/emulator" -version